#!/usr/bin/env bash

function absdirname
{
	if (( $# != 1 ))
	then
		echo 'Usage: absdirname path'
		exit 1
	fi

	pushd "$(dirname "$1")" > /dev/null
	pwd
	popd > /dev/null
}

VIM_DIR="$(dirname $(absdirname "$0"))"

git -C "$VIM_DIR" submodule update --init --recursive
ln -s "$VIM_DIR/tools/"vim-{infect,cure} ~/bin
